[package]
name = "gitrev"
version = "0.1.0"
authors = ["Jakub Konka <kubkon@jakubkonka.com>"]

[dependencies]
docopt = "*"
rustc-serialize = "*"
time = "*"

[lib]
name = "gitrev"
path = "src/lib.rs"

[[bin]]
name = "gitrev"
path = "src/main.rs"
